### ISSUE TITLE
View Plans Error

### ISSUE THREAD

**Issue by Ravisondagar** [abhishek6262/Resume-Builder#2]
ErrorException thrown with message "Trying to get property 'amount' of non-object (View: D:\xampp\htdocs\Resume-Builder\resources\views\pages\payment-plans.blade.php)"

**Comment by Ravisondagar** [comment]
sole Error

**Comment by abhishek6262** [comment]
@Ravisondagar seems like you didn't setup the payment plans in Flutterwave Rave.

**Comment by vnsur** [comment]
can help me, setup it? on Hosting share
